sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=espdlucas/jeitin
    - REGISTRY_USER=espdlucas
    # - REGISTRY_PASS=...
    # - DOCKER_HOST=75.101.224.76
    # - DOCKER_HOST_USR=lucas

addons:
  ssh_known_hosts: 
    - 75.101.224.76

before_script:
  - mkdir -p ~/bin && curl -sSL -o ~/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x ~/bin/jq
  - export PATH=$PATH:~/bin
  - jq --version
  - version="$(jq -r '.version' ./package.json)"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" -f ./.docker/prod/Dockerfile .
  #- docker tag 

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: develop

after_deploy:
  - echo "$VM_SSH_KEY" | base64 -d > lucas.pem
  - chmod 400 lucas.pem
  - ssh -i lucas.pem $DOCKER_VM_USR@75.101.224.76
  - source /home/lucas/.bashrc
  - dockerconnect
  - docker pull "${IMAGE_NAME}:${version}" 
  - docker kill $(docker ps -q)
  - docker run -d -p 80:"$PORT"
    --env PORT="$PORT"
    --env DB_NAME="$DB_NAME"
    --env DB_HOST="$DB_HOST"
    --env DB_USERNAME="$DB_USERNAME"
    --env DB_PASSWORD="$DB_PASSWORD"
    --env DB_PORT="$DB_PORT"
    "${IMAGE_NAME}:${version}"
  - exit
  - exit