version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_prod
    container_name: jeitin-prod
    image: jeitin/prod
    environment:
      - PORT=80
    networks:
      - prod-network
    ports:
      - '5555:80'

networks:
  prod-network:
    driver: bridge
