version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    container_name: jeitin-dev
    image: jeitin/dev
    volumes:
      - ./src:/home/node/jeitin/src
    environment:
      - PORT=5555
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
