version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/prod/Dockerfile
    container_name: jeitin-prod
    image: jeitin/prod
    environment:
      - PORT=9001
      - AUTH_CALLBACK_URL=http://localhost:9001
      - DB_HOST=docker.for.mac.localhost # Mac-only DNS name for localhost, will resolve to the internal IP address used by the host.
    networks:
      - prod-network
    ports:
      - '9001:9001'

networks:
  prod-network:
    driver: bridge
