# basic config
host:
  port: 8080

database:
  type: mssql
  host: localhost
  port: 5432
  username: sa
  password: jXCU0uTXgOAa
  database: urlshort
  synchronize: true
  logging: false

# Remove this, sample extra config
sample:
  title: A full node backend
