# basic config
host:
  port: 8080

database:
  type: mssql
  host: localhost
  port: 1433
  username: sa
  password: jXCU0uTXgOAa
  database: urlftw
  synchronize: true
  logging: false

# Remove this, sample extra config
sample:
  title: urlftw
